/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type BalanceHuman = {
  Native: Coin[];
} | {
  Cw20: Cw20Coin;
};
export type Uint128 = string;
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {
    [k: string]: unknown;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface DetailsResponse {
  balance: BalanceHuman;
  expires: Expiration;
  hash: string;
  id: string;
  recipient: string;
  source: string;
  [k: string]: unknown;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface Cw20Coin {
  address: string;
  amount: Uint128;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  create: CreateMsg;
} | {
  release: {
    id: string;
    preimage: string;
    [k: string]: unknown;
  };
} | {
  refund: {
    id: string;
    [k: string]: unknown;
  };
} | {
  receive: Cw20ReceiveMsg;
};
export type Binary = string;
export interface CreateMsg {
  expires: Expiration;
  hash: string;
  id: string;
  recipient: string;
  [k: string]: unknown;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  [k: string]: unknown;
}
export interface ListResponse {
  swaps: string[];
  [k: string]: unknown;
}
export type QueryMsg = {
  list: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  details: {
    id: string;
    [k: string]: unknown;
  };
};